name: Scenario Bug Report
description: Submit a report about a problem with Reforged Eden 2.
labels: ["new"]
body:
- type: markdown
  attributes:
    value: "> [!IMPORTANT]\n> **Before reporting any issue, please first search for your issue here on GitHub (don't forget to look at closed issues as well) and then read over the troubleshooting steps located on the Workshop at the following link:**\n> https://steamcommunity.com/workshop/filedetails/discussion/2550354956/3807281445021139863/\n> \n> If those steps were not able to fix your issue or were not relevant, please fill out this bug report to the best of your ability. Providing as much detailed information as possible will make it easier for us to fix the problem.\n> \n> **This form is only for submitting reports about problems with the Reforged Eden 2 scenario. We are unable to assist with issues with dedicated servers, other scenarios, or game bugs. If you have feedback or questions about the scenario please see the Workshop. If your report is about a game bug or isn't filled out properly it will be closed.**\n> \n> For Game Bugs please see:\n> https://empyriononline.com/forums/bugs.24/\n> \n> For server assistance please see the pinned discussions here:\n> https://steamcommunity.com/sharedfiles/filedetails/discussions/3143225812\n> \n> For issues with other scenarios please contact the scenario author."

- type: markdown
  attributes:
    value: "\n# \n# Required Information:\n*Basic information about your report.*"
- type: markdown
  attributes:
    value: "*Reminder before reporting any issue to please do a quick search to see if your issue was already posted here on GitHub (don't forget to search closed issues as well) and read over the troubleshooting thread posted on the Workshop:* https://steamcommunity.com/workshop/filedetails/discussion/2550354956/3807281445021139863/"
- type: input
  id: build
  attributes:
    label: Reforged Eden 2 Build Number
    description: "What is your RE2 build number? You can find the RE2 build number on the player inventory window in-game or on the loading screen.\nCompare your build number versus the one in the latest change notes posted at https://steamcommunity.com/sharedfiles/filedetails/changelog/3143225812.\nIf you're unable to load the scenario put NA as the answer.\n*If your scenario is out of date or your issue was already fixed your report may be closed.*"
    placeholder: "ex 1234"
  validations:
    required: true
- type: dropdown
  id: mode
  attributes:
    label: "Game mode"
    description: "Game modes where the issue occurs. You can select multiple options.\n*Co-op is not recommended. If playing on a server you may first want to contact your server owner as this may be a server configuration problem rather than a scenario problem.*"
    multiple: true
    options:
      - Single Player
      - Co-op
      - Dedicated Server
  validations:
    required: true

- type: textarea
  id: issue
  attributes:
    label: What is the issue
    description: "Please provide a detailed description of what the problem is. Make sure to include any relevant information needed."
    placeholder: "ex I get an error popup anytime I shoot the Advanced Pistol, Project Eden Prologue mission does not complete when talking to captain, game crashes when warping to R class planets."
  validations:
    required: true
- type: textarea
  id: errorcode
  attributes:
    label: Error code from console or log (Optional)
    description: "If there is an error shown in your console or logs, please copy and paste or describe the error here. Please do not upload your entire game log, only the relevant part with the error."
    placeholder: "ex Playfieldtype not found for playfield Eta Delta, Unknown Mesh xxxx/yyyy"
  validations:
    required: false

- type: markdown
  attributes:
    value: "\n# \n# Optional Information:\nOptional information that is relevant to help narrow down the issue.\n*Sections not relevant can be left blank.*"
- type: input
  id: poiname
  attributes:
    label: POI Name
    description: "Exact spawn name of the POI that has a problem."
    placeholder: "ex Kennex Station, Lost Colony."
- type: input
  id: pfname
  attributes:
    label: Playfield Name
    description: "Name of the planet, moon, or sector where the issue occurs."
    placeholder: "ex Sienna, Delta IV, Epsilon Rho"
- type: input
  id: pftype
  attributes:
    label: Playfield Class
    description: "Class of the planet, moon, or sector where the issue occurs. You can find the playfield class on the map description."
    placeholder: "ex Temperate, Rocky Desert, Poor Quality Asteroid Field"
- type: input
  id: starname
  attributes:
    label: Star Name
    description: "Name of the star system from the galaxy map where the issue occurs."
    placeholder: "ex Alpha, Beta, Neyta Rho"
- type: input
  id: starclass
  attributes:
    label: Star Class
    description: "Class of the star system from the galaxy map where the issue occurs. Appears on the galaxy map in brackets next to the name."
    placeholder: "ex G2, B, O3, F"
- type: input
  id: mission
  attributes:
    label: Mission Name
    description: "Name of the mission that has a problem. Please include the full mission name as seen in the PDA."
    placeholder: "ex The Dead type 5, Project Eden Prologue"
- type: input
  id: objective
  attributes:
    label: Mission Objective
    description: "Name or description of the mission objective that has a problem."
    placeholder: "ex Finding Dead type 5 planet, warping to UCH Research Vessel."


- type: markdown
  attributes:
    value: "\n \nThank you so much for taking the time to make a report. We will reply as soon as possible."
