name: Scenario Bug Report
description: Submit a report about a problem with Reforged Eden 2.
title: "[Bug]: "
labels: ["bug", "new"]
projects: ["Reforged Eden 2"]
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: input
  id: prevalence
  attributes:
    label: Bug prevalence
    description: "How often do you or others encounter this bug?"
    placeholder: "Whenever I visit the user account page (1-2 times a week)"
  validations:
    required: true
