name: Scenario Bug Report
description: Submit a report about a problem with Reforged Eden 2.
title: "[Bug]: "
labels: ["bug", "new"]
body:
- type: markdown
  attributes:
    value: "## Please read first!"
- type: markdown
  attributes:
    value: "**Thank you for taking the time to report a problem with Reforged Eden 2! Before reporting any issue, please read over the standard troubleshooting steps located here:** https://steamcommunity.com/workshop/filedetails/discussion/2550354956/3807281445021139863/"
- type: input
  id: build
  attributes:
    label: Reforged Eden 2 Build Number
    description: "What is the RE2 build number? You can find the RE2 build number on the player inventory window in-game or on the loading screen."
    placeholder: "ex 1234"
  validations:
    required: true
- type: checkboxes
  id: mode
  attributes:
    label: "Game mode"
    description: "Game mode where the issue occurs. Note that playing Reforged Eden 2 in co-op is not recommended."
    options:
      - label: Single Player
      - label: Co-op
      - label: Dedicated Server
- type: input
  id: pfname
  attributes:
    label: Playfield Name
    description: "Name of the planet, moon, or sector where the issue occurs. (Optional)"
    placeholder: "ex Sienna, Delta IV, Epsilon Rho"
- type: input
  id: pftype
  attributes:
    label: Playfield Class
    description: "Class of the planet, moon, or sector where the issue occurs. You can find the playfield class on the map description. (Optional)"
    placeholder: "ex Temperate, Rocky Desert, Poor Quality Asteroid Field"
- type: input
  id: starname
  attributes:
    label: Star Name
    description: "Name of the star system from the galaxy map where the issue occurs. (Optional)"
    placeholder: "ex Alpha, Beta, Neyta Rho"
- type: input
  id: starclass
  attributes:
    label: Star Class
    description: "Class of the star system from the galaxy map where the issue occurs. Appears on the galaxy map in brackets next to the name. (Optional)"
    placeholder: "G2, B, O3, F"
