name: Scenario Bug Report
description: Submit a report about a problem with Reforged Eden 2.
title: "[Bug]: "
labels: ["bug", "new"]
body:
- type: markdown
  attributes:
    value: "> [!IMPORTANT]\n> Please read first\n> **Before reporting any issue, please read over the troubleshooting steps located on the Workshop here:**\nhttps://steamcommunity.com/workshop/filedetails/discussion/2550354956/3807281445021139863/\n> If those steps were not able to fix your issue or were not relevant, please fill out this bug report to the best of your ability. Providing as much detailed information as possible will make it easier for us to fix the problem.\n> **This form is only for submitting reports about problems with the Reforged Eden 2 scenario. We are unable to assist with issues from other scenarios or with game bugs. If your report is about a game bug or isn't filled out properly it will be closed.**"

- type: markdown
  attributes:
    value: "# Basic Information!"
- type: checkboxes
  id: readtroubleshoot
  attributes:
    label: Important Troubleshooting Information
    description: "Before reporting any issue, please read over the troubleshooting thread posted here: https://steamcommunity.com/workshop/filedetails/discussion/2550354956/3807281445021139863/"
    options:
      - label: I have read the troubleshooting thread.
        required: true
- type: input
  id: build
  attributes:
    label: Reforged Eden 2 Build Number
    description: "What is the RE2 build number? You can find the RE2 build number on the player inventory window in-game or on the loading screen."
    placeholder: "ex 1234"
  validations:
    required: true
- type: checkboxes
  id: mode
  attributes:
    label: "Game mode"
    description: "Game mode where the issue occurs. Note that playing Reforged Eden 2 in co-op is not recommended."
    options:
      - label: Single Player
      - label: Co-op
      - label: Dedicated Server
- type: input
  id: pfname
  attributes:
    label: Playfield Name (Optional)
    description: "Name of the planet, moon, or sector where the issue occurs."
    placeholder: "ex Sienna, Delta IV, Epsilon Rho"
- type: input
  id: pftype
  attributes:
    label: Playfield Class (Optional)
    description: "Class of the planet, moon, or sector where the issue occurs. You can find the playfield class on the map description."
    placeholder: "ex Temperate, Rocky Desert, Poor Quality Asteroid Field"
- type: input
  id: starname
  attributes:
    label: Star Name (Optional)
    description: "Name of the star system from the galaxy map where the issue occurs."
    placeholder: "ex Alpha, Beta, Neyta Rho"
- type: input
  id: starclass
  attributes:
    label: Star Class (Optional)
    description: "Class of the star system from the galaxy map where the issue occurs. Appears on the galaxy map in brackets next to the name."
    placeholder: "G2, B, O3, F"
