blank_issues_enabled: false
contact_links:
  - name: Reforged Eden 2 Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3143225812
    about: See the Workshop for any questions about the scenario. GitHub should only be used for reporting scenario bugs.
